GET http://localhost:3000/assignment HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTQxMjc1YjQ3OTBiZDJkOWMyNjg5MSIsIm5hbWUiOiJzY290dCIsImVtYWlsIjoic2NvdHRAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaXNUZWFjaGVyIjp0cnVlLCJpYXQiOjE2MzcwOTU1NTQsImV4cCI6MTYzNzE4MTk1NH0.ddDQBqwAk_VEDJfDplBt8O84gJiErgYLlcf8cg97e-E
###
GET http://localhost:3000/user/request HTTP/1.1
###
POST http://localhost:3000/assignment HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTQxMjc1YjQ3OTBiZDJkOWMyNjg5MSIsIm5hbWUiOiJzY290dCIsImVtYWlsIjoic2NvdHRAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaXNUZWFjaGVyIjp0cnVlLCJpYXQiOjE2MzcwOTU1NTQsImV4cCI6MTYzNzE4MTk1NH0.ddDQBqwAk_VEDJfDplBt8O84gJiErgYLlcf8cg97e-E
Content-Type:   application/json

{
    "description": "create a method",
    "deadline": "2021-11-18",
    "track": "backend",
    "submissionLink": "http://localhost:3000/assignment/submit"
}
  
#   "userId": "61941275b4790bd2d9c26891