GET http://localhost:3000/assignment HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTU1MTFmYzVmNDE5N2U0ZmMyMWZiOSIsIm5hbWUiOiJzY290dCIsImVtYWlsIjoic2NvdHRAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaXNUZWFjaGVyIjp0cnVlLCJpYXQiOjE2MzcxNzU5ODMsImV4cCI6MTYzNzI2MjM4M30.7gfc7HpPLUmJKJcTv58ezvB5yBwaz863Ueg8_hj7M1Q
###
GET http://localhost:3000/teacher/students HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTU1MTFmYzVmNDE5N2U0ZmMyMWZiOSIsIm5hbWUiOiJzY290dCIsImVtYWlsIjoic2NvdHRAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaXNUZWFjaGVyIjp0cnVlLCJpYXQiOjE2MzcxNzU5ODMsImV4cCI6MTYzNzI2MjM4M30.7gfc7HpPLUmJKJcTv58ezvB5yBwaz863Ueg8_hj7M1Q
###
POST http://localhost:3000/assignment HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTU1MTFmYzVmNDE5N2U0ZmMyMWZiOSIsIm5hbWUiOiJzY290dCIsImVtYWlsIjoic2NvdHRAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaXNUZWFjaGVyIjp0cnVlLCJpYXQiOjE2MzcxNzU5ODMsImV4cCI6MTYzNzI2MjM4M30.7gfc7HpPLUmJKJcTv58ezvB5yBwaz863Ueg8_hj7M1Q
Content-Type:   application/json

{
    "description": "create a method",
    "deadline": "2021-11-18",
    "track": "backend",
    "submissionLink": "http://localhost:3000/assignment/submit"
}

###
GET http://localhost:3000/teacher/students HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTU1MTFmYzVmNDE5N2U0ZmMyMWZiOSIsIm5hbWUiOiJzY290dCIsImVtYWlsIjoic2NvdHRAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaXNUZWFjaGVyIjp0cnVlLCJpYXQiOjE2MzcxNzU5ODMsImV4cCI6MTYzNzI2MjM4M30.7gfc7HpPLUmJKJcTv58ezvB5yBwaz863Ueg8_hj7M1Q

###
GET http://localhost:3000/teacher/promote/6195515ec5f4197e4fc21fc2 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTU1MTFmYzVmNDE5N2U0ZmMyMWZiOSIsIm5hbWUiOiJzY290dCIsImVtYWlsIjoic2NvdHRAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaXNUZWFjaGVyIjp0cnVlLCJpYXQiOjE2MzcxNzU5ODMsImV4cCI6MTYzNzI2MjM4M30.7gfc7HpPLUmJKJcTv58ezvB5yBwaz863Ueg8_hj7M1Q

###
#   "teacher": "6195511fc5f4197e4fc21fb9
#   "user": "6195515ec5f4197e4fc21fc2